### ISSUE TITLE
Python version requirement 3.9

### ISSUE THREAD

**Issue by benkraj** [lenaschimmel/sarscov2recombinants#6]
Thanks for the tool.

Just had a quick note that I think Python 3.9 is required due to the | operator in [dict](https://stackoverflow.com/questions/13361510/typeerror-unsupported-operand-types-for-dict-items-and-dict-items/13361543#13361543).

I was getting an error before trying it with 3.9.

**Comment by lenaschimmel** [comment]
Thanks for mentioning this!

I will change this in an update soon, so that it would work on Python 3.6 as well.

**Comment by lenaschimmel** [comment]
I just pushed an update which should fix it. I hope it works, because couldn't test it with python 3.6, 3.7 or 3.8 yet, as I currently don't have time to sort my python environment issues and only use 3.9.

As a side node: please don't close issues before I fixed them - I need them open to remind me that I still need to do something. (But it can probably remain closed now.)
